spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/jbehave-demo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

server:
  port: 8080